inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

AllCops:
  NewCops: disable
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'bin/*'
    - 'lib/activestorage_docx_previewer.rb'
Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument

Layout/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false

# These cops worsen the readability of code when the expression is longer than the condition
#
# example:
# if somehting.truthy?
#   LengthyCode.new attribute: 1, attribute: 2, attribute: 3, attribute: 4
# end
#
# vs.
#
# LongCode.new attribute: 1, attribute: 2, attribute: 3, attribute: 4 if something.truthy?
#
# Let's leave the decision to the developer rather than enforcing it
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false

# expect more to speed up tests.
RSpec/MultipleExpectations:
  Max: 10

Style/SymbolArray:
  Enabled: false
